#ifndef _CONSTRESOURCE_H
#define _CONSTRESOURCE_H

#include "Const.h"

//consts

#define LOG_STR_FILENAME		"Game.log"

#define CONFIG_STR_FILENAME				"Game.ini"
#define CONFIG_STR_DEFAULTFILENAME		"hge.ini"

#define RESDEFAULT_FONTFILE				"Graphic/font.fnt"
#define RESDEFAULT_FONTFONT				"MS Gothic"

#define RESDEFAULT_DATARESOURCE			"Game_RESOURCE.res"
#define RESDEFAULT_DATABIN				"Game_BIN.databin"
#define RESDEFAULT_DATASCRIPT			"Game_SCRIPT.databin"
#define RESDEFAULT_DATACUSTOMCONST		"Game_CUSTOMCONST.table"
#define RESDEFAULT_DATAMUSICDEFINE		"Game_MUSICDEFINE.table"
#define RESDEFAULT_DATASPRITEDEFINE		"Game_SPRITEDEFINE.table"
#define RESDEFAULT_DATADATADEFINE		"Game_DataTable.table"
#define RESDEFAULT_DATAPACKAGEDEFINE	"Game_PackageTable.table"
#define RESDEFAULT_DATATEXTUREDEFINE	"Game_TextureTable.table"
#define RESDEFAULT_DATAEFFECTDEFINE		"Game_EffectTable.table"
#define RESDEFAULT_DATASEDEFINE			"Game_SETable.table"

#define RESDEFAULT_SCRIPTFOLDER		"Script/"
#define RESDEFAULT_SNAPSHOTFOLDER	"SnapShot/"
#define RESDEFAULT_REPLAYFOLDER		"Replay/"
#define RESDEFAULT_DATAFOLDER		"Data/"

#define RESDEFAULT_SCRIPTEXT7		"script"
#define RESDEFAULT_REPLAYEXT7		"rpy"

//CONFIG
#define RESCONFIGS_RESOURCE				"Resource"
#define RESCONFIGN_RESOURCEFILE			"ResourceFile"
#define RESCONFIGDEFAULT_RESOURCEFILE		""
#define RESCONFIGN_RESBINNAME			"ResourceBinName"
#define RESCONFIGDEFAULT_RESBINNAME			RESDEFAULT_DATARESOURCE
#define RESCONFIGN_PASSWORD				"Password"
#define RESCONFIGDEFAULT_PASSWORD			"h5nc"

#define RESCONFIGS_JOYSETTING	"JoySetting"

#define RESCONFIGS_KEYSETTING	"KeySetting"

#ifdef __WIN32
#else

#ifdef __PSP
#endif // __PSP

#endif // __WIN32

#define RESCONFIGS_VOLUME		"Volume"
#define RESCONFIGN_VOLMUSIC		"Music"
#define RESCONFIGDEFAULT_VOLMUSIC	100
#define RESCONFIGN_VOLSE		"SE"
#define RESCONFIGDEFAULT_VOLSE		100

#define RESCONFIGS_CUSTOM		"Custom"
#define RESCONFIGN_SCREENMODE	"ScreenMode"
#define RESCONFIGDEFAULT_SCREENMODE	0
#define RESCONFIGN_USERNAME		"UserName"
#define RESCONFIGDEFAULT_USERNAME	"NoName"
#define RESCONFIGN_RENDERSKIP	"RenderSkip"
#define RESCONFIGDEFAULT_RENDERSKIP	0

#define RESCONFIGS_CUSTOMWINDOW		"CustomWindow"
#define RESCONFIGN_DEFAULTWINDOW	"DefaultWindow"
#define RESCONFIGDEFAULT_DEFAULTWINDOW	1
#define RESCONFIGN_WINDOWLEFT		"WindowLeft"
#define RESCONFIGDEFAULT_WINDOWLEFT		0
#define RESCONFIGN_WINDOWTOP		"WindowTop"
#define RESCONFIGDEFAULT_WINDOWTOP		0
#define RESCONFIGN_WINDOWWIDTH		"WindowWidth"
#define RESCONFIGDEFAULT_WINDOWWIDTH	640
#define RESCONFIGN_WINDOWHEIGHT		"WindowHeight"
#define RESCONFIGDEFAULT_WINDOWHEIGHT	480
#define RESCONFIGN_WINDOWTOPMOST	"WindowTopMost"
#define RESCONFIGDEFAULT_WINDOWTOPMOST	0

#define RESLOADING_PCK	"Loading.pck"
#define RESLOADING_TEX	"Loading/Loading.tex"

#define SNAPSHOT_PRIFIX		"SnapShot"
#define SNAPSHOT_EXTENSION	"bmp"


#ifdef __WIN32
#define RESCONFIGS_KEYSETTING_1	"KeySetting_1"
#define RESCONFIGS_KEYSETTING_2	"KeySetting_2"
#else
#define RESCONFIGS_KEYSETTING_1	"KeySetting_PSP_1"
#define RESCONFIGS_KEYSETTING_2	"KeySetting_PSP_2"
#endif // __WIN32

#define RESCONFIGN_JOYSHOOT		"JoyFire"
#define RESCONFIGDEFAULT_JOYSHOOT	3
#define RESCONFIGN_JOYJUMP		"JoyJump"
#define RESCONFIGDEFAULT_JOYJUMP	2
#define RESCONFIGN_JOYSUICIDE	"JoySuicide"
#define RESCONFIGDEFAULT_JOYSUICIDE	7
#define RESCONFIGN_JOYSPECIAL	"JoySpecial"
#define RESCONFIGDEFAULT_JOYSPECIAL	6
#define RESCONFIGN_JOYPAUSE		"JoyPause"
#define RESCONFIGDEFAULT_JOYPAUSE	1
#define RESCONFIGN_JOYRETRY		"JoyRetry"
#define RESCONFIGDEFAULT_JOYRETRY	8
#define RESCONFIGN_DEBUG_JOYSPEEDUP	"Debug_JoySpeedUp"
#define RESCONFIGDEFAULT_DEBUG_JOYSPEEDUP	5

#define RESCONFIGDEFAULT_JOYCOMBINESLOWDRAIN	1

#define RESCONFIGN_KEYUP		"KeyUp"
#define RESCONFIGN_KEYDOWN		"KeyDown"
#define RESCONFIGN_KEYLEFT		"KeyLeft"
#define RESCONFIGN_KEYRIGHT		"KeyRight"
#define RESCONFIGN_KEYSHOOT		"KeyFire"
#define RESCONFIGN_KEYJUMP		"KeyJump"
#define RESCONFIGN_KEYSUICIDE	"KeySuicide"
#define RESCONFIGN_KEYSPECIAL	"KeySpecial"
#define RESCONFIGN_KEYPAUSE		"KeyPause"
#define RESCONFIGN_KEYSKIP		"KeySkip"
#define RESCONFIGN_KEYRETRY		"KeyRetry"
#define RESCONFIGN_KEYENTER		"KeyEnter"
#define RESCONFIGN_KEYESCAPE	"KeyEscape"
#define RESCONFIGN_KEYCAPTURE	"KeyCapture"

#if defined __WIN32 || defined __IPHONE

#define RESCONFIGDEFAULT_KEYUP_1		DIK_UP
#define RESCONFIGDEFAULT_KEYDOWN_1		DIK_DOWN
#define RESCONFIGDEFAULT_KEYLEFT_1		DIK_LEFT
#define RESCONFIGDEFAULT_KEYRIGHT_1		DIK_RIGHT
#define RESCONFIGDEFAULT_KEYSHOOT_1		DIK_Z
#define RESCONFIGDEFAULT_KEYJUMP_1		DIK_LSHIFT
#define RESCONFIGDEFAULT_KEYSUICIDE_1	DIK_Q
#define RESCONFIGDEFAULT_KEYSPECIAL_1	DIK_X
#define RESCONFIGDEFAULT_KEYUP_2		DIK_W
#define RESCONFIGDEFAULT_KEYDOWN_2		DIK_S
#define RESCONFIGDEFAULT_KEYLEFT_2		DIK_A
#define RESCONFIGDEFAULT_KEYRIGHT_2		DIK_D
#define RESCONFIGDEFAULT_KEYSHOOT_2		DIK_J
#define RESCONFIGDEFAULT_KEYJUMP_2		DIK_K
#define RESCONFIGDEFAULT_KEYSUICIDE_2	DIK_I
#define RESCONFIGDEFAULT_KEYSPECIAL_2	DIK_L

#define RESCONFIGDEFAULT_KEYPAUSE	DIK_SPACE
#define RESCONFIGDEFAULT_KEYSKIP	DIK_LCONTROL
#define RESCONFIGDEFAULT_KEYRETRY	DIK_R
#define RESCONFIGDEFAULT_KEYENTER	DIK_RETURN
#define RESCONFIGDEFAULT_KEYESCAPE	DIK_F4
#define RESCONFIGDEFAULT_KEYCAPTURE	DIK_HOME

#elif defined __PSP

#define         _PSP_CTRL_SELECT    0
#define         _PSP_CTRL_START     3
#define         _PSP_CTRL_UP        4
#define         _PSP_CTRL_RIGHT     5
#define         _PSP_CTRL_DOWN      6
#define         _PSP_CTRL_LEFT      7
#define         _PSP_CTRL_LTRIGGER  8
#define         _PSP_CTRL_RTRIGGER  9
#define         _PSP_CTRL_TRIANGLE  12
#define         _PSP_CTRL_CIRCLE    13
#define         _PSP_CTRL_CROSS     14
#define         _PSP_CTRL_SQUARE    15
#define         _PSP_CTRL_HOME      16
#define         _PSP_CTRL_HOLD      17
#define         _PSP_CTRL_NOTE      23
#define			_PSP_CTRL_SCREEN	22
#define			_PSP_CTRL_VOLUP		20
#define			_PSP_CTRL_VOLDOWN	21
#define			_PSP_CTRL_WLAN_UP	18
#define			_PSP_CTRL_REMOTE	19
#define			_PSP_CTRL_DISC		24
#define			_PSP_CTRL_MS		25

#define			_PSP_CTRL_NULL		31
#define			_PSP_CTRL_NULL_QUIT	28

#define RESCONFIGDEFAULT_KEYUP_1		_PSP_CTRL_UP
#define RESCONFIGDEFAULT_KEYDOWN_1		_PSP_CTRL_DOWN
#define RESCONFIGDEFAULT_KEYLEFT_1		_PSP_CTRL_LEFT
#define RESCONFIGDEFAULT_KEYRIGHT_1		_PSP_CTRL_RIGHT
#define RESCONFIGDEFAULT_KEYSHOOT_1		_PSP_CTRL_SQUARE
#define RESCONFIGDEFAULT_KEYJUMP_1		_PSP_CTRL_CROSS
#define RESCONFIGDEFAULT_KEYSUICIDE_1		_PSP_CTRL_RTRIGGER
#define RESCONFIGDEFAULT_KEYSPECIAL_1		_PSP_CTRL_LTRIGGER
#define RESCONFIGDEFAULT_KEYUP_2		_PSP_CTRL_NULL
#define RESCONFIGDEFAULT_KEYDOWN_2		_PSP_CTRL_NULL
#define RESCONFIGDEFAULT_KEYLEFT_2		_PSP_CTRL_NULL
#define RESCONFIGDEFAULT_KEYRIGHT_2		_PSP_CTRL_NULL
#define RESCONFIGDEFAULT_KEYSHOOT_2		_PSP_CTRL_NULL
#define RESCONFIGDEFAULT_KEYJUMP_2		_PSP_CTRL_NULL
#define RESCONFIGDEFAULT_KEYSUICIDE_2		_PSP_CTRL_NULL
#define RESCONFIGDEFAULT_KEYSPECIAL_2		_PSP_CTRL_NULL

#define RESCONFIGDEFAULT_KEYPAUSE	_PSP_CTRL_CIRCLE
#define RESCONFIGDEFAULT_KEYSKIP	_PSP_CTRL_TRIANGLE
#define RESCONFIGDEFAULT_KEYRETRY	_PSP_CTRL_TRIANGLE
#define RESCONFIGDEFAULT_KEYENTER	_PSP_CTRL_SQUARE
#define RESCONFIGDEFAULT_KEYESCAPE	_PSP_CTRL_NULL_QUIT
#define RESCONFIGDEFAULT_KEYCAPTURE	_PSP_CTRL_NULL

#endif	// __WIN32

#define SNAPSHOT_FOLDER		"SnapShot"
#define SNAPSHOT_PRIFIX		"SnapShot"
#define SNAPSHOT_EXTENSION	"bmp"

#endif